# Generated by Django 3.1.12 on 2026-02-20 15:50

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('tutor_id', models.CharField(max_length=24)),
                ('student_id', models.CharField(blank=True, max_length=24, null=True)),
                ('subject_id', models.CharField(max_length=24)),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', djongo.models.fields.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject_ids', djongo.models.fields.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
